[tools]
"aqua:kubevirt/kubevirt/virtctl" = "latest"
"github:Azure/AKSFlexNode" = "latest"
"github:Azure/unbounded" = { version = "latest", matching = "kubectl-unbounded" }
"github:benjajaja/mdfried" = "latest"
"go:github.com/golangci/golangci-lint/v2/cmd/golangci-lint" = "latest"
"go:github.com/phealy/git-credential-azure-cli" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"krew:aks" = "latest"
"krew:apidocs" = "latest"
"krew:ctx" = "latest"
"krew:edit-secret" = "latest"
"krew:node-shell" = "latest"
"krew:ns" = "latest"
"krew:retina" = "latest"
"krew:sniff" = "latest"
"krew:virt" = "latest"
argocd = "latest"
azure = { version = "latest", uvx_args = "--prerelease=allow" }
azure-kubelogin = "latest"
bat = "latest"
cargo-binstall = "latest"
copilot-cli = "latest"
direnv = "latest"
fzf = "latest"
github-cli = "latest"
go = "latest"
helm = "latest"
hugo = "latest"
jq = "latest"
k9s = "latest"
kubecolor = "latest"
kubectl = "latest"
node = "latest"
notation = "latest"
oh-my-posh = "latest"
oras = "latest"
powershell-core = "latest"
python = "latest"
ripgrep = "latest"
rust = "latest"
shellcheck = "latest"
shfmt = "latest"
stern = "latest"
tmux = "latest"
uv = "latest"
websocat = "latest"
yq = "latest"

[settings]
minimum_release_age = "0"
