[tools]
azure = { version = "latest", uvx_args = "--prerelease=allow" }
direnv = "latest"
python = "latest"
uv = "latest"
fzf = "latest"
go = "latest"
"go:github.com/phealy/git-credential-azure-cli" = "latest"
"go:github.com/golangci/golangci-lint/v2/cmd/golangci-lint" = "latest"
jq = "latest"
yq = "latest"
rust = "latest"
shellcheck = "latest"
shfmt = "latest"
powershell-core = "latest"
stern = "latest"
k9s = "latest"
helm = "latest"
kubectl = "latest"
krew = "latest"
github-cli = "latest"
kubecolor = "latest"
oh-my-posh = "latest"
websocat = "latest"
node = "latest"
hugo = "latest"

[settings]
minimum_release_age = "0"
