bind-key - select-layout even-vertical
bind-key 0 select-window -t :10
bind-key C-e setw force-width 0 \; setw force-height 0
bind-key C-w setw force-width 80 \; setw force-height 24
bind-key D detach-client -a
bind-key J command-prompt -p "join pane from:"  "join-pane -s '%%'"
bind-key N command-prompt -p "renumber to:"     "move-window -t '%%'"
bind-key R source-file ~/.tmux.conf \; display-message " Config reloaded..".
bind-key ` send-prefix
bind-key a send-prefix -2
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind-key s command-prompt -p "send pane to:"  "join-pane -t '%%'"
bind-key | select-layout even-horizontal
bind-key S setw synchronize-panes #{?synchronize-panes,off,on}
bind-key T run-shell -Cd 0.25 'send-keys -l " for term in tmux-256color screen-256color tmux screen xterm; do infocmp -x \$term &>/dev/null && export TERM=\"\$term\" && break; done; bash --norc -c \"printf \\\"\\\\033[18t\\\";IFS=\\\";\\\" read -dt -as;stty rows \\\${s[1]} cols \\\${s[2]};printf \\\"\\\\r\\\\033[K\\\"\"\n"'

# Open new windows in the current pane's path
bind c new-window      -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

set -g aggressive-resize on
set -g default-terminal tmux-256color
set -sg terminal-overrides ",*-256color:RGB"
set -ga terminal-overrides ",*-256color:Tc"
set -as terminal-features ',*:sixel'
set -as terminal-features ',*:hyperlinks'
set -g allow-passthrough on
set -g window-size smallest
set -g base-index 1
set -g history-limit 100000
set -g pane-border-format "#{?synchronize-panes, SYNC ──,} #{pane_index} ── #{pane_title} ── #{pane_current_command} "
set -g prefix `
set -g prefix2 C-a 
set -g set-titles on
set -g set-titles-string "#T"
set -g update-environment "DBUS_SESSION_BUS_ADDRESS DISPLAY WAYLAND_DISPLAY WSL2_GUI_APPS_ENABLED WSLENV WSL_DISTRO_NAME WSL_INTEROP SSH_CONNECTION SSH_AUTH_SOCK"
set -s escape-time 25
setw -g mode-keys vi
setw -g mouse off
setw -g xterm-keys on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'jimeh/tmux-themepack'
set -gq @themepack-status-left-area-left-format "#(whoami)"
set -gq @themepack-status-left-area-middle-format "#I"
set -gq @themepack-status-left-area-right-format "#P"
#set -gqF @theme-status-right "#[fg=#{@powerline-status-right-area-right-bg},bg=#{@theme-status-bg}]#[fg=#{@powerline-status-right-area-right-fg},bg=#{@powerline-status-right-area-right-bg},bold] #{@themepack-status-right-area-right-format} "
set -g @themepack 'powerline/default/cyan'
set -gq @theme-status-justify absolute-centre
set -g status-position bottom

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
