#!/usr/bin/bash 

set -uo pipefail 
shopt -s extglob

# Check for contexts that are unreachable
kubectl config get-contexts -o name | xargs -ri bash -c "timeout 5 kubectl --context='{}' version &>/dev/null || kubectl config delete-context '{}'"

# Remove orphan objects
yq -r eval '((.users | map(.name)) - (.contexts | map(.context.user)))[]' <(kubectl config view --raw) | xargs -rL1 kubectl config delete-user | sed -e 's/^/> /'
yq -r eval '((.clusters | map(.name)) - (.contexts | map(.context.cluster)))[]' <(kubectl config view --raw) | xargs -rL1 kubectl config delete-cluster | sed -e 's/^/> /'

# Remove empty KUBECONFIG files
find $HOME/.kube '(' -path "$HOME/.kube/config" -or -path "$HOME/.kube/config.d/*" ')' \
    -type f \
    -execdir bash -c "yq -e eval '.kind == \"Config\" and (.contexts // [] | length) == 0' '{}' &>/dev/null" ';' \
    -delete

printf "Remember to source your shell config to update KUBECONFIG.\n"
