#! /bin/bash

set -eu

TMPFILE=$(mktemp)
trap 'rm $TMPFILE' EXIT
bash --login --noprofile --norc -t -c '. ~/.commonrc; export -p' | sed -e 's/declare -x/export/' | sed -e 's/$/;/g' > $TMPFILE
. $TMPFILE
rm $TMPFILE
export XDG_RUNTIME_DIR=/run/user/$(id -u)

SHELLNAME="$(basename "$(printf '%s' "$SHELL")")"
[[ "$TERM_PROGRAM" == "vscode" ]] && . "$(code --locate-shell-integration-path "${SHELLNAME}")"
